networks:
  mkk_luna_app:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkk_luna_backend
    networks:
      - mkk_luna_app
    ports:
      - "8200:8200"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8200 
    depends_on:
      - postgres
      # - redis
      # - migrations
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:16
    container_name: postgres_mkk_luna
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mkk_luna_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-assigna-user} -d ${POSTGRES_DB:-career-main}"]
      interval: 5s
      timeout: 5s
      retries: 5


  # redis:
  #   image: redis:latest
  #   container_name: redis_iyul
  #   restart: unless-stopped
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - n_app

  migrations:
    build: .
    # env_file:
    #   - .env
    environment:
      - DATABASE_URL=${MIGRATIONS_DATABASE_URL}
      - DOCKER_MIGRATIONS=postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: ["alembic", "upgrade", "head"]
    restart: "no"
    networks:
      - mkk_luna_app




volumes:
  postgres_data:
  # redis_data:
  minio_data: